version: '3'
services:
  web:
    build: ./app
    restart: always
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - TZ=Asia/Taipei  

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "4000:4000"
    depends_on:
      - web
    environment:
      - TZ=Asia/Taipei  

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./mysql/init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - db_data:/var/lib/mysql
    environment:
      - TZ=Asia/Taipei 

volumes:
  db_data:
