"""Initial migration

Revision ID: b0710f7f02c5
Revises: 
Create Date: 2023-08-07 21:20:13.562362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0710f7f02c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postgresql_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clock_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('employeeNumber',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.alter_column('create_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('name')

    with op.batch_alter_table('clock_record', schema=None) as batch_op:
        batch_op.alter_column('employeeNumber',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('update_at')

    op.drop_table('postgresql_model')
    # ### end Alembic commands ###
